# .github/workflows/code-quality.yml
name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters and formatters
        run: |
          pip install black flake8 isort mypy

      - name: Run Black (formatter)
        run: black --check .

      - name: Run Flake8 (linter)
        run: flake8 your_package/ tests/

      - name: Run isort (import sorter)
        run: isort --check-only .

      - name: Run mypy (type checker)
        run: mypy your_package/
