# .github/workflows/test.yml
name: Tests

on: [push, pull_request]

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'

        -   name: Install dependencies
            run: |
                pip install -r requirements.txt
                pip install pytest pytest-cov

        -   name: Run tests with coverage
            run: |
                pytest --cov=your_package tests/
